#! /bin/bash -x

/home/siri/c-beam/c_out/ttsclient.py &
sleep 5

dumpdir=/dump/`date +%Y%m%d%H%M%S`
for partition in $( ls /dev/sdb?* ); 
do
  mount $partition /automount || break
  mkdir -p $dumpdir/`basename $partition` || break
  cp -r /automount/* $dumpdir/`basename $partition`
  umount /automount
done
